# Generated by Django 4.2 on 2023-04-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
