# Generated by Django 4.2 on 2023-04-26 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="end_year",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="question",
            name="start_year",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="question",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.CharField(max_length=200, verbose_name="질문"),
        ),
    ]
